#!/usr/bin/env ruby
# frozen_string_literal: true
$LOAD_PATH << File.expand_path('../lib', __dir__)

require "cleo_quality_review/cli"

##
# Load development environment variables
# This should not be used when packaging in production
if ENV.fetch('CLEO_QUALITY_REVIEW_DEV', 'false') == 'true'
  begin
    require 'dotenv'
    local_dotenv = File.expand_path("../.env.development.local", __dir__)
    Dotenv.load(local_dotenv)
  rescue LoadError
    puts "No local .env.development found. Skip."
  end
end

exit CleoQualityReview::CLI.new(ARGV).run
